package util

import (
	"github.com/joho/godotenv"
)

const (
	DOMAIN                   = "DOMAIN"
	DB_CONN                  = "DB_CONN"
	REDIS_ADDRESS            = "REDIS_ADDRESS"
	SYSTEM_EMAIL             = "SYSTEM_EMAIL"
	EMAIL_APP_PASSWORD       = "EMAIL_APP_PASSWORD"
	SECRET_KEY               = "SECRET_KEY"
	TOKEN_EXPIRATION         = "TOKEN_EXPIRATION"
	REFRESH_TOKEN_EXPIRATION = "REFRESH_TOKEN_EXPIRATION"
	GOOGLE_CLIENT_ID         = "GOOGLE_CLIENT_ID"
	GOOGLE_CLIENT_SECRET     = "GOOGLE_CLIENT_SECRET"
	STRIPE_PUBLISHABLE_KEY   = "STRIPE_PUBLISHABLE_KEY"
	STRIPE_SECRET_KEY        = "STRIPE_SECRET_KEY"
	STRIPE_WEBHOOK_SECRET    = "STRIPE_WEBHOOK_SECRET"
	TELEGRAM_TOKEN           = "TELEGRAM_TOKEN"
)

func LoadConfig(path string) error {
	return godotenv.Load(path)
}
