basePath: /
definitions:
  api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.PaymentIntentResponse:
    properties:
      secret_key:
        type: string
    type: object
  api.StripeConfigResponse:
    properties:
      publishable_key:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for ticket and event management system
  title: Ticket and event management API
  version: "1.0"
paths:
  /api/payment/config:
    get:
      description: Get stripe publishable key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StripeConfigResponse'
      security:
      - BearerAuth: []
      summary: Get stripe publishable key
      tags:
      - payment
  /api/payment/intent:
    post:
      description: Creates a refund to a payment intent. Here, we expect a full refund
      parameters:
      - description: The payment intent id
        in: path
        name: amount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: the refund id
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a new refund
      tags:
      - payment
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
